In [6]:
%load_ext autoreload
%autoreload 2

In [1]:
from baconshor import *

In [2]:
grid = create_grid(3)

In [13]:
Print(grid)

0 0 0
0 0 0
0 0 0


In [3]:
add_y_error(grid, [1,2])

In [15]:
Print(grid)

1 1 0
0 0 0
0 0 0


In [16]:
count_y_errors(grid)

2

In [15]:
check_config_row(grid)
check_config_col(grid)

False

In [20]:
check_stabilizer(grid,[1,2,4,5,7,8])

bye


-1

In [23]:
list_of_grids3_count(3,5)

9

In [24]:
list_of_grids3_grid(3,5)

1 1 1
1 0 0
1 0 0

1 1 1
0 1 0
0 1 0

1 1 1
0 0 1
0 0 1

1 0 0
1 1 1
1 0 0

1 0 0
1 0 0
1 1 1

0 1 0
1 1 1
0 1 0

0 1 0
0 1 0
1 1 1

0 0 1
1 1 1
0 0 1

0 0 1
0 0 1
1 1 1



9

In [9]:
list_of_grids2(5,7,0,True)

1 1 1 0 0
1 0 0 0 0
1 0 0 0 0
0 0 0 1 0
0 0 0 0 1

1 1 1 0 0
1 0 0 0 0
1 0 0 0 0
0 0 0 0 1
0 0 0 1 0

1 1 1 0 0
1 0 0 0 0
0 0 0 1 0
1 0 0 0 0
0 0 0 0 1

1 1 1 0 0
1 0 0 0 0
0 0 0 1 0
0 0 0 0 1
1 0 0 0 0

1 1 1 0 0
1 0 0 0 0
0 0 0 0 1
1 0 0 0 0
0 0 0 1 0

1 1 1 0 0
1 0 0 0 0
0 0 0 0 1
0 0 0 1 0
1 0 0 0 0

1 1 1 0 0
0 1 0 0 0
0 1 0 0 0
0 0 0 1 0
0 0 0 0 1

1 1 1 0 0
0 1 0 0 0
0 1 0 0 0
0 0 0 0 1
0 0 0 1 0

1 1 1 0 0
0 1 0 0 0
0 0 0 1 0
0 1 0 0 0
0 0 0 0 1

1 1 1 0 0
0 1 0 0 0
0 0 0 1 0
0 0 0 0 1
0 1 0 0 0

1 1 1 0 0
0 1 0 0 0
0 0 0 0 1
0 1 0 0 0
0 0 0 1 0

1 1 1 0 0
0 1 0 0 0
0 0 0 0 1
0 0 0 1 0
0 1 0 0 0

1 1 1 0 0
0 0 1 0 0
0 0 1 0 0
0 0 0 1 0
0 0 0 0 1

1 1 1 0 0
0 0 1 0 0
0 0 1 0 0
0 0 0 0 1
0 0 0 1 0

1 1 1 0 0
0 0 1 0 0
0 0 0 1 0
0 0 1 0 0
0 0 0 0 1

1 1 1 0 0
0 0 1 0 0
0 0 0 1 0
0 0 0 0 1
0 0 1 0 0

1 1 1 0 0
0 0 1 0 0
0 0 0 0 1
0 0 1 0 0
0 0 0 1 0

1 1 1 0 0
0 0 1 0 0
0 0 0 0 1
0 0 0 1 0
0 0 1 0 0

1 1 1 0 0
0 0 0 1 0
1 0 0 0 0
1 0 0 0 0
0 0 0 0 1

1 1 1 0 0
0 0 0 1 0
1 0 0 0 0
0

2200

In [2]:
grids = list_of_grids(3)

In [3]:
count_y_logicals_dict(grids,3)

{9: [array([[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]])],
 5: [array([[ True,  True,  True],
         [ True, False, False],
         [ True, False, False]]),
  array([[ True,  True,  True],
         [False,  True, False],
         [False,  True, False]]),
  array([[ True,  True,  True],
         [False, False,  True],
         [False, False,  True]]),
  array([[ True, False, False],
         [ True,  True,  True],
         [ True, False, False]]),
  array([[ True, False, False],
         [ True, False, False],
         [ True,  True,  True]]),
  array([[False,  True, False],
         [ True,  True,  True],
         [False,  True, False]]),
  array([[False,  True, False],
         [False,  True, False],
         [ True,  True,  True]]),
  array([[False, False,  True],
         [ True,  True,  True],
         [False, False,  True]]),
  array([[False, False,  True],
         [False, False,  True],
         [ True,  True,  True]])],
 3: [array([

In [4]:
run(3)

Distance:  3 

weight:  9  | Number of y logicals:  1
1 1 1
1 1 1
1 1 1

weight:  5  | Number of y logicals:  9
1 1 1
1 0 0
1 0 0

1 1 1
0 1 0
0 1 0

1 1 1
0 0 1
0 0 1

1 0 0
1 1 1
1 0 0

1 0 0
1 0 0
1 1 1

0 1 0
1 1 1
0 1 0

0 1 0
0 1 0
1 1 1

0 0 1
1 1 1
0 0 1

0 0 1
0 0 1
1 1 1

weight:  3  | Number of y logicals:  6
1 0 0
0 1 0
0 0 1

1 0 0
0 0 1
0 1 0

0 1 0
1 0 0
0 0 1

0 1 0
0 0 1
1 0 0

0 0 1
1 0 0
0 1 0

0 0 1
0 1 0
1 0 0



In [2]:
table(3,number_of_weights(3))

d = 3:

WEIGHT     # OF VALID GRIDS    
3          6                   
5          9                   
7          0                   
9          1                   


In [4]:
construct_stabilizers(3,grid)

{(0, 3, 1, 4, 2, 5): 1,
 (0, 1, 3, 4, 6, 7): 1,
 (3, 6, 4, 7, 5, 8): 1,
 (1, 2, 4, 5, 7, 8): -1}

In [4]:
construct_stabilizers(3,grid)

{(0, 1, 2, 3, 4, 5): 1,
 (0, 3, 6, 1, 4, 7): 1,
 (3, 4, 5, 6, 7, 8): 1,
 (1, 4, 7, 2, 5, 8): -1}

In [5]:
construct_stabilizers_scipy_I(3)

[[0, 3, 1, 4, 2, 5],
 [0, 1, 3, 4, 6, 7],
 [3, 6, 4, 7, 5, 8],
 [1, 2, 4, 5, 7, 8]]

In [2]:
construct_stabilizers_scipy_I(3)

array([[0, 1, 2, 3, 4, 5],
       [0, 3, 6, 1, 4, 7],
       [3, 4, 5, 6, 7, 8],
       [1, 4, 7, 2, 5, 8]], dtype=object)

In [3]:
construct_stabilizers_scipy_x_errors_I(3)

[[0, 3, 1, 4, 2, 5], [3, 6, 4, 7, 5, 8]]

In [2]:
construct_stabilizers_scipy_x_errors_I(3)

array([[0, 1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7, 8]])

In [1]:
from numpy_baconshor import *

In [2]:
import sys
import numpy as np
from scipy.optimize import milp, LinearConstraint, Bounds, OptimizeResult
import matplotlib.pyplot as plt
import csv
import time
from typing import List, Union
def mle_decoder_bs(M : int, I : List[List[int]], C : List[int], p : Union[List[float], float]) -> OptimizeResult:
    """
    Solves the MLE decoder problem using a MILP solver.

    Parameters:
        - M: Number of binary variables E_j.
        - I: List of lists. I[i] is the set of errors E_j which flip the check C_i
        - C: Constraint values C_i.
        - p: List of probabilities p_j for each E_j.

    Returns:
        - result: The result object from scipy.optimize.milp.
        
    """
    # Validate input data
    N = len(I)
    assert len(C) == N, "Length of C must be N"

    #can remove
    if np.isscalar(p):
        p = np.full(M, p)
    # elif type(p) is List:
    #     assert len(p) == M, "Length of p must be M"
    # else:
    #     raise ValueError('p must be a float or a list of floats')

    # Idea: The decision variable x contains both E_j and K_i values.
    # i.e. x = [E_1, ..., E_M, K_1, ..., K_N]
    # The scipy milp solver minimizes <c, x> where c is the objective function coefficients. 
    # We can ignore the constant log(1-p_j) in the objective function.

    # Construct the objective function coefficients, by default set the K_i coefficients to zero
    # Note the minus sign for the E_i coeffs because the solver minimizes the objective function
    c = np.array([-np.log(p_j) + np.log(1 - p_j) for p_j in p] + [0]*N) #remove since assuming all p are same

    # Construct equality constraints matrix (constraints are Ax = b)
    A_eq = np.zeros((N, M + N)) # N constraints, (M + N) variables
    b_eq = []
    for i in range(N):

        # Constraint for the check, C_i is: \sum_{Ej in I_i} E_j - 2K_i = (1 - C_i)/2
        # where I_i is the set of errors [...,E_j,...] that flip the check C_i
        
        # Firstly, set the matrix elements to pick out the appropriate E_j values
        for j in I[i]:
            if j >= M:
                raise ValueError(f"E_j index {j} exceeds M-1")
            A_eq[i, j] = 1

        # Next, set matrix elements to pick out the corresponding K_i
        A_eq[i, M + i] = -2

        # Lastly, compute the right-hand side (1 - C_i)/2
        b_eq.append((1 - C[i]) / 2)

    # Define constraints (equality constraints)
    constraints = LinearConstraint(A=A_eq, lb=b_eq, ub=b_eq)

    # Bounds: E_j: binary (0-1), K_i: integer >=0
    bounds = Bounds(lb = [0]*M + [0]*N,
                    ub = [1]*M + [np.inf]*N)

    # Integrality: Both E_j and K_i are integers within bounds (i.e. 1)
    integrality = [1]*(M + N)  

    # Solve the MILP
    res = milp(c           = c,
               constraints = constraints,
               integrality = integrality,
               bounds      = bounds)
    
    return M, N, res

def Print_result(M,N,result):
    guess = []
    if result.success:
        print("Optimization successful.")
        print(">> Maximum objective value:", -result.fun)  # Convert back to maximization
        print(">> Optimal E_j values:")
        for j in range(M):
            print(f"\t E_{j+1} = {round(result.x[j])}")
            guess.append(round(result.x[j]))
        print(">> Optimal K_i values:")
        for i in range(N):
            print(f"\t K_{i+1} = {int(result.x[M + i])}")
    else:
        print("No optimal solution found.")
        print("Status:", result.message)
        print("Details:", result.get("message", "No additional information"))

    return guess

def print_result(M,N,result):
    guess = []
    if result.success:
        # print("Optimization successful.")
        # print(">> Maximum objective value:", -result.fun)  # Convert back to maximization
        # print(">> Optimal E_j values:")
        # for j in range(M):
        #     # print(f"\t E_{j+1} = {round(result.x[j])}")
        #     guess.append(round(result.x[j]))
        return np.round(result.x[:M]).astype(int)
        # print(">> Optimal K_i values:")
        # for i in range(N):
        #     print(f"\t K_{i+1} = {int(result.x[M + i])}")
    else:
        print("No optimal solution found.")
        # print("Status:", result.message)
        # print("Details:", result.get("message", "No additional information"))


In [4]:
M = 3
grid = create_grid(3)# no error
add_y_error(grid,[3, 7])
Print(grid, M)
I= construct_stabilizers_scipy_I(M)
I_old = construct_stabilizers_old(M)
C = construct_stabilizers_scipy_C(I, grid)
# print(I)
# print(I_old)
# print(C)
# print(check_stabilizer(grid,I[2]))
# # Particular syndrome measurement
p = 0.1

# # expected_E = [1,0,0]
# # print('Expected E_j values')
# # for j in range(M):
# #     print(f'\t E_{j} = {expected_E[j]}')
# # print()

guess = print_result(*mle_decoder_bs(M**2,I_old,C,p))
Print(guess,M)
solver_accuracy(3,grid,solver_to_grid_scipy(M,guess))

0 0 1
0 0 0
1 0 0
0 0 0
0 1 0
0 0 0


False

In [8]:
from baconshor import *

In [ ]:
M = 3
grid = create_grid(3)# no error
add_y_error(grid,[3, 7])
Print(grid)
I= construct_stabilizers_scipy_I(M)
C = construct_stabilizers_scipy_C(I, grid)
print(I)
print(C)
# print(check_stabilizer(grid,I[2]))
# # Particular syndrome measurement
p = 0.1

# # expected_E = [1,0,0]
# # print('Expected E_j values')
# # for j in range(M):
# #     print(f'\t E_{j} = {expected_E[j]}')
# # print()

guess = print_result(*mle_decoder_bs(M**2,I,C,p))
Print_old(guess)
# solver_accuracy(3,grid,solver_to_grid_scipy(M,guess))

0 0 1 
0 0 0 
1 0 0 
[[0, 3, 1, 4, 2, 5], [0, 1, 3, 4, 6, 7], [3, 6, 4, 7, 5, 8], [1, 2, 4, 5, 7, 8]]
[-1, -1, -1, -1]


TypeError: 'numpy.int64' object is not iterable